apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: security-agent-suite-data
  namespace: security-agent-suite
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
