apiVersion: v1
kind: Service
metadata:
  name: security-agent-suite
  namespace: security-agent-suite
spec:
  selector:
    app: security-agent-suite
  ports:
    - name: http
      port: 8080
      targetPort: http
